/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.adivinanumero.diseno;

import co.com.adivinanumero.logica.LogicaJuego;
import co.com.adivinanumero.logica.NumeroAleatorio;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author dainer
 */
public class JuegoPrincipal extends javax.swing.JFrame {

    //Instancia de objetos
    LogicaJuego log = new LogicaJuego();
    
    /**
     * Creates new form JuegoPrincipal
     */
    public JuegoPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        try {
            anadirNumeros();
            MensajeGameOver.setJFrameAbierto(this);
        } catch (Exception e) {
            e.getMessage();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_cerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jlbl_C3 = new javax.swing.JLabel();
        jlbl_C2 = new javax.swing.JLabel();
        jlbl_C1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtn_menu = new javax.swing.JButton();
        jbtn_pista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harrington", 0, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 119, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("•");
        jLabel1.setToolTipText("");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(22, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(22, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(22, 35));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 30));

        jlbl_cerrar.setFont(new java.awt.Font("Harrington", 0, 55)); // NOI18N
        jlbl_cerrar.setForeground(new java.awt.Color(255, 0, 0));
        jlbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_cerrar.setText("•");
        jlbl_cerrar.setToolTipText("");
        jlbl_cerrar.setFocusable(false);
        jlbl_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbl_cerrar.setMaximumSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.setMinimumSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.setPreferredSize(new java.awt.Dimension(22, 35));
        jlbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jlbl_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn1.setBackground(new java.awt.Color(135, 206, 235));
        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn1.setText("10");
        jbtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn1.setContentAreaFilled(false);
        jbtn1.setFocusPainted(false);
        jbtn1.setFocusable(false);
        jbtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn1.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jbtn2.setBackground(new java.awt.Color(135, 206, 235));
        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn2.setText("2");
        jbtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn2.setContentAreaFilled(false);
        jbtn2.setFocusPainted(false);
        jbtn2.setFocusable(false);
        jbtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn2.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jbtn3.setBackground(new java.awt.Color(135, 206, 235));
        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn3.setText("0");
        jbtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn3.setContentAreaFilled(false);
        jbtn3.setFocusPainted(false);
        jbtn3.setFocusable(false);
        jbtn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn3.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jbtn4.setBackground(new java.awt.Color(135, 206, 235));
        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn4.setText("6");
        jbtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn4.setContentAreaFilled(false);
        jbtn4.setFocusPainted(false);
        jbtn4.setFocusable(false);
        jbtn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn4.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jbtn5.setBackground(new java.awt.Color(135, 206, 235));
        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn5.setText("4");
        jbtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn5.setContentAreaFilled(false);
        jbtn5.setFocusPainted(false);
        jbtn5.setFocusable(false);
        jbtn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn5.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jbtn6.setBackground(new java.awt.Color(135, 206, 235));
        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn6.setText("25");
        jbtn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn6.setContentAreaFilled(false);
        jbtn6.setFocusPainted(false);
        jbtn6.setFocusable(false);
        jbtn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn6.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jbtn9.setBackground(new java.awt.Color(135, 206, 235));
        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn9.setForeground(new java.awt.Color(255, 255, 255));
        jbtn9.setText("21");
        jbtn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn9.setContentAreaFilled(false);
        jbtn9.setFocusPainted(false);
        jbtn9.setFocusable(false);
        jbtn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn9.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jbtn8.setBackground(new java.awt.Color(135, 206, 235));
        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn8.setText("25");
        jbtn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn8.setContentAreaFilled(false);
        jbtn8.setFocusPainted(false);
        jbtn8.setFocusable(false);
        jbtn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn8.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jbtn7.setBackground(new java.awt.Color(135, 206, 235));
        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn7.setText("31");
        jbtn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn7.setContentAreaFilled(false);
        jbtn7.setFocusPainted(false);
        jbtn7.setFocusable(false);
        jbtn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn7.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jlbl_C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/corazon.png"))); // NOI18N
        jPanel2.add(jlbl_C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 30, 30));

        jlbl_C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/corazon.png"))); // NOI18N
        jPanel2.add(jlbl_C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 30, 30));

        jlbl_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/corazon.png"))); // NOI18N
        jPanel2.add(jlbl_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adivina el número");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jbtn_menu.setBackground(new java.awt.Color(135, 206, 235));
        jbtn_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_menu.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_menu.setText("Menu");
        jbtn_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtn_menu.setContentAreaFilled(false);
        jbtn_menu.setFocusPainted(false);
        jbtn_menu.setFocusable(false);
        jbtn_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_menu.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo.png"))); // NOI18N
        jbtn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_menuActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 140, 60));

        jbtn_pista.setBackground(new java.awt.Color(135, 206, 235));
        jbtn_pista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtn_pista.setForeground(new java.awt.Color(135, 206, 235));
        jbtn_pista.setText("Pista");
        jbtn_pista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 206, 235)));
        jbtn_pista.setContentAreaFilled(false);
        jbtn_pista.setFocusPainted(false);
        jbtn_pista.setFocusable(false);
        jbtn_pista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_pista.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtn_pista.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonLargo2.png"))); // NOI18N
        jbtn_pista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pistaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 140, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_menuActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jbtn_menuActionPerformed

    private void jbtn_pistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pistaActionPerformed
        MensajePistaNumero msjp = new MensajePistaNumero(this, true);
        msjp.setVisible(true);
    }//GEN-LAST:event_jbtn_pistaActionPerformed

    private void jlbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jlbl_cerrarMouseClicked
   
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn1.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn2.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn3.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn4.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn5.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn6.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn7.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn8.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        log.validarEleccion(Integer.parseInt(this.jbtn9.getText()), getLabels(), this);
    }//GEN-LAST:event_jbtn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPrincipal().setVisible(true);
            }
        });
    }

    // ----- Metodos creados por Dainer -----
    
    private void anadirNumeros() {
        try {
            NumeroAleatorio.generarNumeros(9, 1, 30);
            NumeroAleatorio.OrdenarNumeros(NumeroAleatorio.getArregloN());

            int[] num = NumeroAleatorio.getArregloN();

            jbtn1.setText(Integer.toString(num[0]));
            jbtn2.setText(Integer.toString(num[1]));
            jbtn3.setText(Integer.toString(num[2]));
            jbtn4.setText(Integer.toString(num[3]));
            jbtn5.setText(Integer.toString(num[4]));
            jbtn6.setText(Integer.toString(num[5]));
            jbtn7.setText(Integer.toString(num[6]));
            jbtn8.setText(Integer.toString(num[7]));
            jbtn9.setText(Integer.toString(num[8])); 
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    private JLabel[] getLabels() {
        JLabel[] jlbl = { this.jlbl_C3, this.jlbl_C2, this.jlbl_C1 };
        
        return jlbl;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtn_menu;
    private javax.swing.JButton jbtn_pista;
    private javax.swing.JLabel jlbl_C1;
    private javax.swing.JLabel jlbl_C2;
    private javax.swing.JLabel jlbl_C3;
    private javax.swing.JLabel jlbl_cerrar;
    // End of variables declaration//GEN-END:variables
}
